### ISSUE TITLE
Bop music player 1.2: crashes when I trying to add songs from "files" menu by creating a new playlist name using an emoji

### ISSUE THREAD

**Issue by sagorahmed** [iamSahdeep/Bop#45]
**Describe the bug**
The crash happens when I trying to add songs by creating a new playlist name using emoji from the "Files" menu.

**To Reproduce**
1. Go to the 'Files' menu
2. Tap on a song's folder
3. Click "PLAY ALL"
4. Tap on the very first ⋮ (Three dots/ Vertical ellipsis) and click "Save Playlist" to save these songs to a playlist.
5. Then, create a playlist like this format "☺️ best" (at first an "Emoji", then space, then write something).
6. See error. (If it won't work, you can produce that bug by deleting those playlists and creating a new one with same playlist name as you created before with emoji).

**Expected behavior**
Users should be able to create a playlist like this way without the app crashing. I think giving an emoji as a playlist's name is a good way to feel about that playlist's songs. I Belive an emoji worth a thousand words.

**Screenshots**
![bug](https://media.giphy.com/media/8FuMmNtkpOjbQIW6lp/giphy.gif)

**Informations:**
 - Device: Samsung A5
 - OS: Android 6.0.1
 - Version: Bop music player v1.2

**Additional context**
Logcat
```
03-29 13:18:56.961 31539 31539 D AndroidRuntime: Shutting down VM

03-29 13:18:56.961 31539 31539 E AndroidRuntime: FATAL EXCEPTION: main

03-29 13:18:56.961 31539 31539 E AndroidRuntime: Process: com.sahdeepsingh.Bop, PID: 31539

03-29 13:18:56.961 31539 31539 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.sahdeepsingh.Bop/com.sahdeepsingh.Bop.Activities.MainScreen}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.sahdeepsingh.Bop.services.ServicePlayMusic.isPlaying()' on a null object reference

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4221)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4323)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.sahdeepsingh.Bop.services.ServicePlayMusic.isPlaying()' on a null object reference

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at com.sahdeepsingh.Bop.Activities.MainScreen.onResume(MainScreen.java:385)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1287)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7015)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4210)

03-29 13:18:56.961 31539 31539 E AndroidRuntime: 	... 10 more
```

**Comment by iamSahdeep** [comment]
hello @sagorahmed the issue is not with emoji i guess, I am also making playlist with emojis. Also i can see in logat the issue is in the onresume method where is am checking if music is being played or not. Which is throwing NPE which is now resolved in latest build, sill soon release. 
![look this SS of playlists with emojis](https://user-images.githubusercontent.com/26563213/55279241-5292b400-533c-11e9-9171-d5b32e7fa89b.png)

**Comment by sagorahmed** [comment]
Hello @iamSahdeep , I also noticed as you mentioned. But you can produce that bug by deleting those playlists and creating a new one with same playlist name as you created before.

**Comment by iamSahdeep** [comment]
@sagorahmed can you verify if issue is still there in v1.2.1

**Comment by sagorahmed** [comment]
Hello @iamSahdeep, Yes, this issue is still there. But I think this issue is not with emoji, I have found another one that related to this. I will let you know by opening a new issue as soon as possible.

**Comment by iamSahdeep** [comment]
shifted to #46
